version: '3'

tasks:
  e2e:
    cmds:
      - docker compose -f ./apps/internal-api/docker/compose.e2e.yaml up --build --force-recreate --exit-code-from e2e-runner
      - defer: docker compose -f ./apps/internal-api/docker/compose.e2e.yaml rm --force --volumes
