FROM node:18.10.0-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
CMD ["ash", "-c", "npx prisma migrate reset --force && npx jest --runInBand --config=./jest-e2e.config.json"]
