name: End to end tests

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker-compose -f ./docker/docker-compose.e2e.yaml up --exit-code-from e2e-runner
