name: Publish Games Deals API

on:
  push:
    tags:
      - api/v*.*.*

jobs:
  publish-api:
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      image-name: mikolajkalwa/gamesdeals/api
      dockerfile-path: ./apps/internal-api/Dockerfile
      tag-prefix: api
    secrets: inherit
