name: Publish Games Deals Bot

on:
  push:
    tags:
      - bot/v*.*.*

jobs:
  publish-bot:
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      image-name: mikolajkalwa/gamesdeals/bot
      dockerfile-path: ./apps/bot/Dockerfile
      tag-prefix: bot
    secrets: inherit
