name: Publish Games Deals Notifier

on:
  push:
    tags:
      - notifier/v*.*.*

jobs:
  publish-notifier:
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      image-name: mikolajkalwa/gamesdeals/notifier
      dockerfile-path: ./apps/notifier/Dockerfile
      tag-prefix: notifier
    secrets: inherit
